name: wellyess
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Hive dependencies
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Svg support dependencies
  flutter_svg: ^2.1.0  # Aggiunto per supportare SVG


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icons/calendar.svg
  - assets/icons/heartbeat.svg
  - assets/icons/pills.svg
  - assets/icons/sport_food.svg
  - assets/images/elder_profile_pic.png
  - assets/logo/wellyess.png