name: wellyess
description: "Benessere per tutte le età"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Hive dependencies
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  hive_generator: ^2.0.0

  # Shared Preferences dependencies
  shared_preferences: ^2.2.3 

  # Provider dependencies
  provider: ^6.1.2

  # Svg support dependencies
  flutter_svg: ^2.1.0  # Aggiunto per supportare SVG

  # Line Chart dependencies
  fl_chart: ^1.0.0  

  # Date and Time dependencies
  intl: ^0.18.1  # Per la formattazione delle date

  # Notifications dependencies
  flutter_local_notifications: ^17.0.0 

  # Alarm Manager dependencies
  android_alarm_manager_plus: ^4.0.7

  # Timezone dependencies
  timezone: ^0.9.2  # Per gestire i fusi orari

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.13.0    # ← aggiungi il package

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Logo.png"  # ← il tuo logo
  android_min_sdk: 21                  # ← evita di leggere build.gradle

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/