name: wellyess
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Hive dependencies
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  hive_generator: ^2.0.0

  # Shared Preferences dependencies
  shared_preferences: ^2.2.3 


  # Svg support dependencies
  flutter_svg: ^2.1.0  # Aggiunto per supportare SVG

  # Line Chart dependencies
  fl_chart: ^1.0.0  

  # Date and Time dependencies
  intl: ^0.20.2  # Per la formattazione delle date

  # Notifications dependencies
  flutter_local_notifications: ^19.3.0  

  # Timezone dependencies
  timezone: ^0.10.0  # Per gestire i fusi orari

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
  - assets/icons/ # permette di usare tutte le icone SVG
  - assets/images/ # permette di usare tutte le immagini
  - assets/logo/ # permette di usare il logo dell'app